title: Basic drawing in Scratch
hero_image: images/banner.png
description: Lifting the up and downn to draw in Scratch
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: 
technologies: "scratch"
steps:
  - title: Using the pen
